Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,15 +1,28 @@
-name: Genius-an
+name: hello-world
 
-on: push
+on:
+  push:
 
 jobs:
   my-job:
     runs-on: ubuntu-latest
     steps:
-     
-      - name: Checkout repository
+      - name: Checkout code
         uses: actions/checkout@v2
 
-     
-      - name: Print text from index.js
-        run: cat dist/index.js
+      - name: Set Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '18'
+          
+      - name: Install packages
+        run: npm install
+
+      - name: Run testing
+        run: |
+          output=$(node dist/Test1.js)
+
+          if [ $output -ne 0 ]; then
+            echo "Error: code $output"
+            exit 1
+          fi
